// generator/templates/apps/spa/frontends/vue/src/App.vue
<script setup>
import { onMounted, ref } from 'vue'

const info = ref(null)
const error = ref(null)

onMounted(async () => {
  try {
    const res = await fetch('/api/version')
    info.value = await res.json()
  } catch (err) {
    error.value = String(err)
  }
})
</script>

<template>
  <main class="app">
    <h1>Goose + Vue</h1>
    <p>
      This page is served by the Goose SPA platform. The backend answers
      JSON under <code>/api</code>.
    </p>
    <p v-if="info" class="status">
      Backend says: <strong>{{ info.name }}</strong> v{{ info.version }}
    </p>
    <p v-if="error" class="error">Backend unreachable: {{ error }}</p>
  </main>
</template>

// generator/templates/apps/spa/frontends/react/src/App.jsx
import { useEffect, useState } from 'react'

export default function App() {
  const [info, setInfo] = useState(null)
  const [error, setError] = useState(null)

  useEffect(() => {
    fetch('/api/version')
      .then((res) => res.json())
      .then(setInfo)
      .catch((err) => setError(String(err)))
  }, [])

  return (
    <main className="app">
      <h1>Goose + React</h1>
      <p>
        This page is served by the Goose SPA platform. The backend answers
        JSON under <code>/api</code>.
      </p>
      {info && (
        <p className="status">
          Backend says: <strong>{info.name}</strong> v{info.version}
        </p>
      )}
      {error && <p className="error">Backend unreachable: {error}</p>}
    </main>
  )
}
