// generator/templates/apps/spa/frontends/svelte/src/App.svelte
<script>
  let info = $state(null)
  let error = $state(null)

  $effect(() => {
    fetch('/api/version')
      .then((res) => res.json())
      .then((data) => (info = data))
      .catch((err) => (error = String(err)))
  })
</script>

<main class="app">
  <h1>Goose + Svelte</h1>
  <p>
    This page is served by the Goose SPA platform. The backend answers
    JSON under <code>/api</code>.
  </p>
  {#if info}
    <p class="status">
      Backend says: <strong>{info.name}</strong> v{info.version}
    </p>
  {/if}
  {#if error}
    <p class="error">Backend unreachable: {error}</p>
  {/if}
</main>

// generator/templates/apps/spa/frontends/ng/src/app/app.component.ts
import { Component, OnInit, signal } from '@angular/core';

interface VersionInfo {
  name: string;
  version: string;
}

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <main class="app">
      <h1>Goose + Angular</h1>
      <p>
        This page is served by the Goose SPA platform. The backend answers
        JSON under <code>/api</code>.
      </p>
      @if (info(); as i) {
        <p class="status">
          Backend says: <strong>{{ i.name }}</strong> v{{ i.version }}
        </p>
      }
      @if (error(); as e) {
        <p class="error">Backend unreachable: {{ e }}</p>
      }
    </main>
  `,
})
export class AppComponent implements OnInit {
  readonly info = signal<VersionInfo | null>(null);
  readonly error = signal<string | null>(null);

  ngOnInit(): void {
    fetch('/api/version')
      .then((res) => res.json())
      .then((data: VersionInfo) => this.info.set(data))
      .catch((err) => this.error.set(String(err)));
  }
}
